name: dungeondice
description: A sample command-line application.
version: 0.1.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.5

dependencies:
  mockito: ^5.3.0

